copyright: Apache License v2.0
description: Shared components for Hue
name: ccs-shared
sources: [
  Source/JFrameFilters/CCS.JFrame.ArtButtons.js,
  Source/JFrameFilters/CCS.JFrame.NoOverflow.js,
  Source/JFrameFilters/CCS.JFrame.FormRequest.js,
  Source/JFrameFilters/CCS.JFrame.SplitView.js,
  Source/JFrameFilters/CCS.JFrame.Tabs.js,
  Source/JFrameFilters/CCS.JFrame.ContextMenu.js,
  Source/JFrameFilters/CCS.JFrame.Clearfix.js,
  Source/JFrameFilters/CCS.JFrame.AutoRefresh.js,
  Source/JFrameFilters/CCS.JFrame.DoubleClickDelegate.js,
  Source/JFrameFilters/CCS.JFrame.SubmitOnChange.js,
  Source/JFrameFilters/CCS.JFrame.Collapsible.js,
  Source/JFrameFilters/CCS.JFrame.FormValidator.js,
  Source/JFrameFilters/CCS.JFrame.ToggleHistory.js,
  Source/JFrameFilters/CCS.JFrame.Tips.js,
  Source/JFrameFilters/CCS.JFrame.OverText.js,
  Source/JFrameFilters/CCS.JFrame.HtmlTable.js,
  Source/JFrameFilters/CCS.JFrame.DataGroupToggle.js,
  Source/JFrameFilters/CCS.JFrame.SelectWithOther.js,
  Source/JFrameFilters/CCS.JFrame.Input.js,
  Source/JFrameFilters/CCS.JFrame.SizeTo.js,
  Source/JFrameFilters/CCS.JFrame.FilterInput.js,
  Source/JFrameFilters/CCS.JFrame.FitText.js,
  Source/Fx/Fx.Shake.js,
  Source/JFrameRenderers/CCS.JFrame.Alert.js,
  Source/JFrameRenderers/CCS.JFrame.Prompt.js,
  Source/JFrameRenderers/CCS.JFrame.PartialRefresh.js,
  Source/CCS/CCS.ContextMenu.js,
  Source/CCS/CCS.js,
  Source/CCS/CCS.JBrowser.js,
  Source/CCS/CCS.Error.js,
  Source/CCS/CCS.JFrame.js,
  Source/CCS/CCS.Request.js,
  Source/CCS/CCS.SideScroller.js,
  Source/CCS/CCS.SolidWindow.js,
  Source/CCS/CCS.DropDown.js,
  Source/CCS/CCS.Desktop.js,
  Source/CCS/CCS.Desktop.FlashMessage.js,
  Source/CCS/CCS.Desktop.Config.js,
  Source/CCS/CCS.Dock.js,
  Source/CCS/CCS.Desktop.Keys.js,
  Source/CCS/CCS.User.js,
  Source/CCS/CCS.Login.js,
  Source/JFrameFilters/CCS.JFrame.SideBySideSelect.js,
  Source/Forms/Form.Request.JSON.js,
  Source/Forms/EditInline.js,
  Source/UI/StickyWin.Drawer.js,
  Source/UI/StickyWin.UI.Solid.js,
  Source/UI/ThumbTack.js,
  Source/JFrameLinkers/CCS.JFrame.Target.js,
  Source/JFrameLinkers/CCS.JFrame.CheckAllOrNone.js,
  Source/JFrameLinkers/CCS.JFrame.Nav.js,
  Source/JFrameLinkers/CCS.JFrame.PromptAndPost.js,
  Source/JFrameLinkers/CCS.JFrame.ConfirmAndPost.js,
  Source/JFrameLinkers/CCS.JFrame.Refresh.js,
  Source/JFrameLinkers/CCS.JFrame.FakeRefresh.js,
  Source/JFrameLinkers/CCS.JFrame.Chooser.js,
  Source/Native/String.CCS.js,
  Source/Native/Element.Data.js,
  Source/StaticThirdParty/DynamicTextarea.js,
  Source/CCS/CCS.PostEditor.Simple.js,
  Source/UI/ART.SideBySideSelect.js,
  Source/BehaviorFilters/Behavior.FitText.js,
  Source/BehaviorFilters/Behavior.SideBySideSelect.js,
  Source/BehaviorFilters/Behavior.SizeTo.js,
  Source/BehaviorFilters/Behavior.HtmlTableKeys.js,
  Source/BehaviorFilters/Behavior.ContextMenu.js
]
version: Unknown
